version: "3"
services:
    dtnrpc:
        build:
            context: .
        privileged: true
        cap_add:
            - NET_ADMIN
        tmpfs:
            - /tmp:exec,mode=777
        environment:
            - DISPLAY
            - BACKEND
            - CAP=dtnrpc
            - IDLE=-1
